/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TebakAngkaWindow extends javax.swing.JFrame {

    int angkaSoal;
    int jumlah = 0;

    /**
     * Creates new form TebakAngkaWindow
     */
    public TebakAngkaWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        petunjukLabel = new javax.swing.JLabel();
        inputAngkaTextField = new javax.swing.JTextField();
        cekAngkaButton = new javax.swing.JButton();
        keteranganLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/tebakAngka.png"))); // NOI18N

        mulaiButton.setText("Mulai");
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        petunjukLabel.setText("Klik Tombol Mulai");

        inputAngkaTextField.setEnabled(false);
        inputAngkaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAngkaTextFieldActionPerformed(evt);
            }
        });

        cekAngkaButton.setText("Are You Sure?");
        cekAngkaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekAngkaButtonActionPerformed(evt);
            }
        });

        keteranganLabel.setText("^_^");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(cekAngkaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(petunjukLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(inputAngkaTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(mulaiButton))
                            .addComponent(keteranganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mulaiButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(petunjukLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputAngkaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cekAngkaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(keteranganLabel)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        // TODO add your handling code here:
        angkaSoal = generateAngka();
        petunjukLabel.setText("Masukan angka antara 1 - 100") ;
        inputAngkaTextField.setEnabled(true);
    }//GEN-LAST:event_mulaiButtonActionPerformed

    private void cekAngkaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekAngkaButtonActionPerformed
        // TODO add your handling code here:
        try{
        String tebakanString = inputAngkaTextField.getText();
        int tebakan = Integer.parseInt(tebakanString);
        
        if(tebakan == angkaSoal){
            petunjukLabel.setText("Deabak!!");
            inputAngkaTextField.setEnabled(false);
            mulaiButton.setEnabled(true);
            if(jumlah==1){
                keteranganLabel.setText("Kamu menebak "+jumlah+" kali, Kamu memang LUAR BIASA");
            }else{
                keteranganLabel.setText("Kamu menebak "+jumlah+" kali, Kamu ga mahir -_-");
            }
        }else{
            String message;
            if(tebakan<angkaSoal)
                message = "Angka anda lebih kecil. Coba lebih besar";
            else
                message = "Angka anda lebih besar. Coba lebih kecil";
            petunjukLabel.setText(message);
        }
        //inputAngkaTextField.setText("");
        jumlah++;
        }catch(Exception e){
            //petunjukLabel.setText("Masukan ANGKA, ngerti angka ga?");
            JOptionPane.showMessageDialog(rootPane, "Masukan ANGKA, ngerti angka ga? hayoo fokuss");
        }
    }//GEN-LAST:event_cekAngkaButtonActionPerformed

    private void inputAngkaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAngkaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAngkaTextFieldActionPerformed

    private int generateAngka() {
        double random = Math.random() * 100;
        double ceilValue = Math.ceil(random);
        int generatedAngkaSoal = (int) ceilValue;
        return generatedAngkaSoal;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakAngkaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakAngkaWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekAngkaButton;
    private javax.swing.JTextField inputAngkaTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel keteranganLabel;
    private javax.swing.JButton mulaiButton;
    private javax.swing.JLabel petunjukLabel;
    // End of variables declaration//GEN-END:variables
}
